apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-backend.fullname" . }}
  labels:
    {{- include "fastapi-backend.labels" . | nindent 4 }}
  {{- if .Values.monitoring.serviceMonitor.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.targetPort }}"
    prometheus.io/path: "{{ .Values.monitoring.serviceMonitor.path }}"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fastapi-backend.selectorLabels" . | nindent 4 }}